### ISSUE TITLE
Demo Maybe ? :D

### ISSUE THREAD

**Issue by Rezaabdi78** [joserocha3/firebase-storage-react-dropzone#2]
Hey there; Your tutorial was very useful for me. thx a lot
I had an idea, wouldn't it be better that you released a demo of your app (just the part you used React and Chakra I mean)? so people would see how is the outcome of the code despite you didn't put any screenshots of your product on website.
thanks a lot again, you were a lot of help for my project

**Comment by joserocha3** [comment]
Hi @Rezaabdi78, thank you for the kind words. I went ahead and updated [blog post 1](https://pablorocha.me/blog/firebase-storage-react-dropzone-1) and [blog post 2](https://pablorocha.me/blog/firebase-storage-react-dropzone-2) with links to the code deployed on Netlify. Links are towards the top of the posts.

Demos are pretty simple, so I did not add screenshots.
